### PR TITLE
Added support for units, multipliers and instances

### LINKED ISSUE #2: 4.1 log format changed
Log messages not contains Instance field and store data from multiple instances in the same message id. 
For example XKF1 now contains log from all EKF lanes...

### PR DESCRIPTION
**Pull request by jwithelm**
This is a huge overhaul of the plotjuggler-apbin-plugin with many code changes!

Plotjuggler-apbin-plugin now reads and uses

- units (FMTU and UNIT messages)
- multipliers (FMTU and MULT messages)

and applies them to the message data.

The plugin handles instances defined by the unit character '#'. Instances are now displayed correctly in PlotJuggler (fixes #2).

The plugin tries to convert the time base to unix time (based on the logged data from GNSS). This is useful if you want to analyze rosbags and ArduPilot logfiles in parallel.

This pull request also includes the changes in #1 (closes #1).

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Hello Pierre, Jonas worked with us while developing this PR. We tested it in real world log files together with ROS bags and it works great.

**Comment by khancyr** [comment]
That is awesome! I never had time to look on this.
I will try to review this soon. With this feature we should be able to request the pluggin to be into the official repo!

**Comment by amilcarlucas** [comment]
Please merge this in. It has been waiting for 1,5 years.

**Comment by amilcarlucas** [comment]
@khancyr any progress on this?

**Comment by Georacer** [comment]
I just compiled this one and it works a treat! Thanks! It's so nice to finally be able to use PlotJuggler for Ardupilot again.

**Comment by amilcarlucas** [comment]
Thanks Pierre

**Pull request merged**
